/*  THIS FILE WAS GENERATED BY THE TUXERA RELIANCE EDGE CONFIGURATION UTILITY.
    DO NOT MODIFY.

    Generated by configuration utility version 2.5
*/
/** @file
*/
#include <redconf.h>
#include <redtypes.h>
#include <redmacs.h>
#include <redvolume.h>


const VOLCONF gaRedVolConf[REDCONF_VOLUME_COUNT] =
{
    { 256U, 524288U, 0U, false, 10U, 3U }
};
